version: '2.27'

services:
  database:
    image: mysql:latest
    container_name: testcraft-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testcraft
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3300:3306"
    
  backend:
    build: ./express-backend
    container_name: testcraft-backend
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: testcraft
    ports:
      - "8000:8000"

  frontend:
    build: ./react-frontend
    container_name: testcraft-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend